# Generated by Django 2.2.4 on 2019-08-13 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190813_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='active_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='prepaidplans', to='backend.Prepaidplans'),
        ),
    ]
